package forestry.api.apiculture;

public enum EnumBeeChromosome {
	SPECIES, SPEED, LIFESPAN, FERTILITY, TEMPERATURE_TOLERANCE, NOCTURNAL, HUMIDITY, // DO NOT USE!
	HUMIDITY_TOLERANCE,
	TOLERANT_FLYER,
	CAVE_DWELLING,
	FLOWER_PROVIDER,
	FLOWERING,
	TERRITORY,
	EFFECT
}
